In [9]:
import pandas as pd
import numpy as np
from sklearn import svm
import pickle
from sklearn import model_selection

In [10]:
hedge = pd.read_csv('hedge.csv', header=None)
not_hedge = pd.read_csv('not_hedge_small.csv', header=None)

In [11]:
not_hedge.head()

0      1      2      3      4      ...  22496  22497  22498  22499  22500
0    120     95    111    109    105  ...     76     69     75     93      0
1     37     31     41      5    184  ...      0      0      0      0      0
2    146    146    146    146    146  ...     52     52     53    116      0
3    181    180    180    181    181  ...      4      3      9     13      0
4    112     79     48     52    110  ...    118     78    139    122      0

[5 rows x 22501 columns]

In [13]:
both = pd.concat([hedge,not_hedge])

In [14]:

both.head()

0      1      2      3      4      ...  22496  22497  22498  22499  22500
0     72     58     46     50     54  ...    183    211    206    162      1
1    158    169    140    132    132  ...    178    154    200    117      1
2    255    255    255    255    255  ...    255    255    255    255      1
3    255    255    255    255    255  ...    255    255    255    255      1
4    255    255    255    255    255  ...    255    255    255    255      1

[5 rows x 22501 columns]

In [15]:
from sklearn.utils import shuffle
both = shuffle(both)

In [26]:
X = both.iloc[:,:-1]
Y = both.iloc[:,-1:]

[[ 76  64  82 ...  37  38  38]
 [255 255 255 ... 255 255 255]
 [202 224 249 ... 100  81 102]
 ...
 [105 120 118 ... 108 106 103]
 [  9   9  12 ... 161 164 154]
 [255 255 255 ... 255 255 255]]


In [27]:
X_train, X_test, Y_train, Y_test = model_selection.train_test_split(X.values, Y.values, test_size=0.3, random_state=100)

In [28]:
classifier = svm.SVC()
classifier.fit(X_train, Y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [29]:
from sklearn import metrics
Y_pred = classifier.predict(X_test)

In [31]:
print(metrics.accuracy_score(Y_test, Y_pred))

0.8173374613003096


In [32]:
model_file = 'recogniser'
pickle.dump(classifier, open(model_file, 'wb'))